allowBuilds:
  esbuild: true
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - "@effect/platform-node-shared"
  - "@effect/platform-node"
  - effect
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.2
  vite-plus: 0.3.2
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
